name: MSYS2
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        cpp_version: [ c++11, c++14, c++17, c++20, c++23, c++26 ]
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # updated on Jan 16
    - uses: msys2/setup-msys2@61f9e5e925871ba6c9e3e8da24ede83ea27fa91f # v2.27.0 
      with:
        msystem: UCRT64
        update: true
        install: mingw-w64-ucrt-x86_64-gcc
    - run: |
        g++ -std=${{ matrix.cpp_version }} -g test.cpp -o test.exe
      shell: msys2 {0}
    - name: running test.exe
      run: timeout 10 ./test.exe
      shell: msys2 {0}
