name: MSYS2
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: msys2/setup-msys2@v2.24.1
      with:
        msystem: UCRT64
        update: true
        install: mingw-w64-ucrt-x86_64-gcc
    - run: |
        g++ -std=c++2b -g test.cpp -o test.exe
      shell: msys2 {0}
    - name: running test.exe
      run: timeout 10 ./test.exe
      shell: msys2 {0}
